#!/usr/bin/env node
/*
 * COOP·AUDIT·AI — versioned packer.
 *
 * On every run it bumps the version, stamps it into package.json and
 * src/version.js (shown in the app + exe banner), rebuilds the React app,
 * and packs the standalone Windows exe to release/COOP-AUDIT-AI.exe — fully
 * offline (reuses the cached nexe Node base binary, no downloads).
 *
 * Usage:
 *   node scripts/pack.mjs            → bump PATCH (V2.0.0 → V2.0.1)
 *   node scripts/pack.mjs --minor    → bump MINOR (V2.0.x → V2.1.0)
 *   node scripts/pack.mjs --major    → bump MAJOR (V2.x.x → V3.0.0)
 *   node scripts/pack.mjs --set 2.0.0→ set an exact version (no bump)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const pkgPath = path.join(root, 'package.json');
const verPath = path.join(root, 'src', 'version.js');

const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
const args = process.argv.slice(2);

let [maj, min, pat] = (pkg.version || '0.0.0')
  .split('.')
  .map((n) => parseInt(n, 10) || 0);

const setIdx = args.indexOf('--set');
if (setIdx !== -1 && args[setIdx + 1]) {
  [maj, min, pat] = args[setIdx + 1].split('.').map((n) => parseInt(n, 10) || 0);
} else if (args.includes('--major')) {
  maj += 1;
  min = 0;
  pat = 0;
} else if (args.includes('--minor')) {
  min += 1;
  pat = 0;
} else {
  pat += 1; // default: patch bump on every pack
}

const version = `${maj}.${min}.${pat}`;
const label = `V${maj}.${min}.${pat}`;

// Stamp the new version everywhere.
pkg.version = version;
writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
writeFileSync(
  verPath,
  `// AUTO-GENERATED by scripts/pack.mjs on every \`npm run pack:exe\` — do not edit by hand.\n` +
    `// Single source of truth for the version shown in the app and the exe banner.\n` +
    `export const APP_VERSION = '${label}';\n`
);

console.log(`\n▶  Packing COOP·AUDIT·AI ${label}\n`);

const run = (cmd) => execSync(cmd, { cwd: root, stdio: 'inherit' });
run('npm run build');
run(
  'npx nexe server.cjs -t windows-x64-14.15.3 -r "dist/**/*" -o release/COOP-AUDIT-AI.exe'
);

console.log(`\n✔  release/COOP-AUDIT-AI.exe rebuilt as ${label}\n`);
