// AUTO-GENERATED by scripts/pack.mjs on every `npm run pack:exe` — do not edit by hand.
// Single source of truth for the version shown in the app and the exe banner.
export const APP_VERSION = 'V2.0.0';
